### ISSUE TITLE
create-user-db should prevent (re-)creating existing databases

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#120] opened 2015-10-07 09:38 UTC
looks like i can create the same db over and over again:

```
root@aardwolf:/usr/lib/check_mk_agent/local# create-user-db user-d34db33f
success! Created user-d34db33f, replica_uid: 28372728099e43088a64ddf01d7320e3
root@aardwolf:/usr/lib/check_mk_agent/local# sudo -u soledad-admin create-user-db user-d34db33f
success! Created user-d34db33f, replica_uid: 28372728099e43088a64ddf01d7320e3
root@aardwolf:/usr/lib/check_mk_agent/local# sudo -u soledad-admin create-user-db user-d34db33f
success! Created user-d34db33f, replica_uid: 28372728099e43088a64ddf01d7320e3

```

**Comment by shyba** [comment] 2015-10-07 12:59
As far as I can tell, this is expected.
Looking at this code:
```
    @classmethod                                                                                                                                                                                             
    def open_database(cls, url, create, replica_uid=None, ensure_ddocs=False):                                                                                                                               
        """                                                                                                                                                                                                  
        Open a U1DB database using CouchDB as backend.                                                                                                                                                       
                                                                                                                                                                                                             
        :param url: the url of the database replica                                                                                                                                                          
        :type url: str                                                                                                                                                                                       
        :param create: should the replica be created if it does not exist?                                                                                                                                   
        :type create: bool                                                                                                                                                                                   
        :param replica_uid: an optional unique replica identifier                                                                                                                                            
        :type replica_uid: str                                                                                                                                                                               
        :param ensure_ddocs: Ensure that the design docs exist on server.                                                                                                                                    
        :type ensure_ddocs: bool                                                                                                                                                                             
                                                                                                                                                                                                             
        :return: the database instance                                                                                                                                                                       
        :rtype: CouchDatabase                                                                                                                                                                                
        """                                                                                                                                                                                                  
        # get database from url                                                                                                                                                                              
        m = re.match('(^https?://[^/]+)/(.+)$', url)                                                                                                                                                         
        if not m:                                                                                                                                                                                            
            raise InvalidURLError                                                                                                                                                                            
        url = m.group(1)                                                                                                                                                                                     
        dbname = m.group(2)                                                                                                                                                                                  
        with couch_server(url) as server:                                                                                                                                                                    
            try:                                                                                                                                                                                             
                server[dbname]                                                                                                                                                                               
            except ResourceNotFound:                                                                                                                                                                         
                if not create:                                                                                                                                                                               
                    raise DatabaseDoesNotExist()                                                                                                                                                             
                server.create(dbname)                                                                                                                                                                        
        return cls(                                                                                                                                                                                          
            url, dbname, replica_uid=replica_uid, ensure_ddocs=ensure_ddocs)  
```
You can see that it checks if the database exists before entering on "if not create". It is expected and in the case which the database was already created it would be hard to check at this point (create-user-db).

It is ok to run this twice. In fact, running it for the second time will ensure that all design documents are there, which is a good thing since it can fix problems caused by temporary database outage (this behaviour was known as 'retry' on Tapicero).

I agree that the message is misleading. Do you think that `success! Ensured existence of user-d34db33f, replica_uid: 28372728099e43088a64ddf01d7320e3` would sound better?

**Comment by shyba** [comment] 2015-10-28 22:00
Closed as explained and the status message changed to this one on last PR.

**Closed by shyba** 2015-10-28 22:00 UTC
Labels: 0 - Backlog
