### ISSUE TITLE
InvalidAuthTokenError on dev.pixelated-project.org

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-platform#162] opened 2016-02-16 13:16 UTC
I tried to login to dev.pixelated-project.org, but the login fails (@mnandri  can confirm):

```
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: 2016-02-16 14:15:09 [leap.soledad.client.api] ERROR Soledad exception when syncing!
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: *--- Failure #13719 ---
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: Failure: leap.soledad.common.errors.InvalidAuthTokenError:
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: *--- End of Failure #13719 ---
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: 2016-02-16 14:15:09 [tornado.application] ERROR Exception in callback <functools.partial object at 0x7fbdc891c050>
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: Traceback (most recent call last):
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/zmq/eventloop/minitornado/ioloop.py", line 603, in _run_callb
ack
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: ret = callback()
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/zmq/eventloop/minitornado/stack_context.py", line 275, in nul
l_wrapper
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: return fn(*args, **kwargs)
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: File "/usr/share/python/pixelated-user-agent/src/leap.common/src/leap/common/events/client.py", line 398, in <lambda>
Feb 16 14:15:09 dev1 pixelated-user-agent[15726]: self._loop.add_callback(lambda: callback(event, *content))

```

**Comment by varac** [comment] 2016-02-16 13:19
restarting pixelated-server helped, but we should fix this solidly of course.

**Comment by cz8s** [comment] 2016-02-22 10:54
duplicate of https://github.com/pixelated/pixelated-user-agent/issues/615

**Closed by cz8s** 2016-02-22 10:54 UTC
Labels: 0 - Backlog, bug
